### PR TITLE
Fix urls in various places throughout the contributing guide

### PR DESCRIPTION
**Pull request by gawbul**
There appears to be a number of outdated URLs in the contributing guide. This PR should fix them.

### CODE REVIEW

**Comment by gawbul** [comment]
Hey @choldgraf 👋 

I noticed you were last to commit a change here. Okay to review this when you have the time? Or recommend someone else I can ping?

**Comment by gawbul** [comment]
Is it possible to get added to the pyOpenSci repo at all so I can submit PRs directly rather than forking? @lwasser

**Comment by lwasser** [comment]
hi there @gawbul thank you for this pr!

i'm happy to add you to the org but still would prefer that pr's come in via forks vs lots of branches  accumulating here  as lots  of  people  conribute! it will keep things cleaner over  time!

**Comment by gawbul** [comment]
> hi there @gawbul thank you for this pr!

My pleasure ☺️ 
 
> i'm happy to add you to the org but still would prefer that pr's come in via forks vs lots of branches accumulating here as lots of people conribute! it will keep things cleaner over time!

That's awesome, thank you so much 🙏 You can actually set up GitHub to [automatically delete branches on merge](https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches), but I'm happy to do things whichever way you prefer and fits in with your current process 🙂 I understand you can't give everyone permissions for the project, or individual repos for that matter, so a forking model makes sense. It adds a bit more overhead for the contributor to keep their branch updated, but that's not a major issue. I might put up a blog post on how to keep different remotes up-to-date with each other via the command line actually 🤔

**Comment by lwasser** [comment]
thank you for this  contribution  @gawbul  !! merging!

**Pull request merged**
