### PR TITLE
Add GitHub Actions and CircleCI for CI options

### PR DESCRIPTION
**Pull request by willingc**
GitHub Actions with its ability to support all 3 major OS has become the de facto CI choice in the past year.

### CODE REVIEW

**Comment by choldgraf** [comment]
Good point - we may actually want to remove Travis CI from that list, because it has terms of service that are much less usable for open source projects (and I assume this would also apply to open science projects)

**Comment by lwasser** [comment]
@willingc  and @choldgraf YES! i'm all for removing travis. i've been  moving all of our projects away from travis given their new terms.

**Comment by lwasser** [comment]
i will merge this now but open to more edits and did plan to work on the this guide over the next few weeks too. i started with the editor guide!

**Comment by lwasser** [comment]
thank you for this contribution @willingc !!!

**Pull request merged**
